#!/usr/bin/env bash

set -e

ENV=.deployment_virtualenv
# version of fusionbox-fabric-helpers to run
HELPERS_COMMIT=40418b031ecf79c802110b2827f05b9d61210344
HELPERS_COMMIT_FILE=$ENV/HELPERS_COMMIT

if command -v python2 > /dev/null 2> /dev/null
then
    EXE=$(command -v python2)
elif python --version 2>&1 | grep -E "^Python 2" > /dev/null
then
    EXE=$(command -v python)
fi

if [ -z "$EXE" ]
then
    echo "Couldn't find Python 2" > /dev/stderr
    exit 127
fi

if [ ! -d $ENV ]
then
  virtualenv -p "$EXE" $ENV
  touch $HELPERS_COMMIT_FILE
fi

# shellcheck disable=SC1090
source $ENV/bin/activate
if [ "$HELPERS_COMMIT" != "$(cat $HELPERS_COMMIT_FILE)" ]
then
  pip install fabric -e "git+https://github.com/fusionbox/fusionbox-fabric-helpers@$HELPERS_COMMIT#egg=fusionbox-fabric-helpers" >/dev/null
  echo $HELPERS_COMMIT > $HELPERS_COMMIT_FILE
fi
exec fab "$@"
