# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 21:14
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('airmozilla', '0002_auto_20180412_2227'),
    ]

    operations = [
        CreateExtension('unaccent'),
        migrations.RunSQL(
            """
            CREATE TEXT SEARCH CONFIGURATION english_unaccent (COPY = english);
            ALTER TEXT SEARCH CONFIGURATION english_unaccent
                ALTER MAPPING FOR hword, hword_part, word
                WITH unaccent, english_stem;
            """,
            """
            DROP TEXT SEARCH CONFIGURATION english_unaccent;
            """
        ),
        migrations.AddField(
            model_name='event',
            name='fulltext',
            field=django.contrib.postgres.search.SearchVectorField(default=''),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='event',
            index=django.contrib.postgres.indexes.GinIndex(fields=['fulltext'], name='airmozilla__fulltex_fa87ab_gin'),
        ),
    ]
