# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airmozilla', '0004_fulltext_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ends_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
