# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airmozilla', '0005_auto_20180418_1636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
