# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 16:40
from __future__ import unicode_literals

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airmozilla', '0006_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_key', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=355)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('fulltext', django.contrib.postgres.search.SearchVectorField()),
            ],
        ),
        migrations.AddIndex(
            model_name='event',
            index=django.contrib.postgres.indexes.GinIndex(fields=['fulltext'], name='airmozilla__fulltex_fa87ab_gin'),
        ),
    ]
