#!/bin/bash

# Load Nubis settings
NUBIS_STACK=$(nubis-metadata NUBIS_STACK)
NUBIS_ENVIRONMENT=$(nubis-metadata NUBIS_ENVIRONMENT)

# Build our Consul prefix
CONSUL_PREFIX="$NUBIS_STACK/$NUBIS_ENVIRONMENT"

# Load our settings (confd called us after generating this)
# shellcheck disable=SC1091
. /etc/nubis-config/airmofront.sh

# Generate our App secret if there isn't one already

if [ "$APP_SECRET_KEY" == "Null" ] || [ "$APP_SECRET_KEY" = "" ]; then
    APP_SECRET_KEY=$(uuidgen)
    consulate kv set "$CONSUL_PREFIX/config/APP_SECRET_KEY" "$APP_SECRET_KEY"

    # We changed something in Consul, we'll get re-invoked shortly
    exit 0
fi


