#!/bin/bash

# Load Nubis settings
NUBIS_STACK=$(nubis-metadata NUBIS_STACK)
NUBIS_ENVIRONMENT=$(nubis-metadata NUBIS_ENVIRONMENT)

# Build our Consul prefix
CONSUL_PREFIX="$NUBIS_STACK/$NUBIS_ENVIRONMENT"

# Perform necessary DB migrations
# We use consul lock to ensure we never run this in parallel across instances

consul lock "$CONSUL_PREFIX/migrate" \
    /var/www/airmofront/manage.py migrate
